typography_spectrum: 0.46191
color:
  brandColors:
    - '#0f140e'
    - '#193b1c'
    - '#142811'
    - '#2d4514'
    - '#365b1a'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75634
analytics:
  google: null
  facebook: null
  twitter: null
name: mffx
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: mainframefx Post & Filmproduction
    id: f9118af7-9535-4697-93e7-115ab955ed28
    type: content
favicon: null
title: null
purpose: []
