name: mffx
favicon: null
layout_spectrum: 0.60974
typography_spectrum: 0.46191
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f140e'
    - '#193b1c'
    - '#142811'
    - '#2d4514'
    - '#365b1a'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
