name: mffx
favicon: null
layout_spectrum: 0.38084
typography_spectrum: 0.46191
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0e3e8'
    - '#546f80'
    - '#1b1b1b'
    - '#414046'
    - '#989c9b'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
