name: mffx
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5902931264135987
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#30c478'
    - '#ffffff'
    - '#c69431'
    - '#3262c4'
    - '#99e0b8'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
