name: mffx
favicon: null
layout_spectrum: 0.75054
typography_spectrum: 0.8934
title: mainframe goes wild
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#30c478'
    - '#ffffff'
    - '#c69431'
    - '#3262c4'
    - '#99e0b8'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
